# NÓS / POSTOS DE SAÚDE
nos = [
    "ALENCAR",
    "BORGES",
    "CENTRO",
    "DUARTE",
    "ESTEVES",
    "FREIRE",
    "GOMES",
    "HOLANDA",
    "INACIO",
    "JACINTO",
    "KAISER",
    "LACERDA",
    "MACEDO",
    "NOGUEIRA",
    "OLIVEIRA",
    "PACHECO",
    "QUEIROZ",
    "RIBEIRO",
    "SILVA",
    "TEIXEIRA",
    "UCHOA",
    "VASCONCELOS",
    "WAGNER",
    "XAVIER",
    "YORK",
    "ZAMBONI",
]

# ORDEM CRESCENTE
grafoCrescente = [
    ["GOMES", "RIBEIRO"],  # 0
    ["JACINTO", "PACHECO", "QUEIROZ"],
    ["JACINTO", "KAISER", "TEIXEIRA", "XAVIER"],
    ["MACEDO"],
    ["MACEDO", "YORK"],
    ["OLIVEIRA", "WAGNER"],
    ["ALENCAR"],
    ["NOGUEIRA"],
    ["QUEIROZ"],
    ["BORGES", "CENTRO", "SILVA"],
    ["CENTRO", "MACEDO", "YORK"],
    ["OLIVEIRA", "PACHECO", "UCHOA"],
    ["DUARTE", "ESTEVES", "KAISER", "NOGUEIRA"],
    ["HOLANDA", "MACEDO", "TEIXEIRA"],
    ["FREIRE", "LACERDA", "XAVIER"],
    ["BORGES", "LACERDA"],
    ["BORGES", "INACIO"],
    ["ALENCAR", "TEIXEIRA"],
    ["JACINTO", "YORK", "ZAMBONI"],
    ["CENTRO", "NOGUEIRA", "RIBEIRO", "WAGNER"],
    ["LACERDA"],
    ["YORK"],
    ["FREIRE", "TEIXEIRA"],
    ["CENTRO", "OLIVEIRA"],
    ["ESTEVES", "KAISER", "SILVA", "VASCONCELOS"],
    ["SILVA"],
]

# ORDEM DECRESCENTE
grafoDecrescente = [
    ["RIBEIRO","GOMES"],  # 0
    ["QUEIROZ", "PACHECO", "JACINTO"],
    ["XAVIER","TEIXEIRA", "JACINTO"],
    ["MACEDO"],
    ["YORK", "MACEDO"],
    ["WAGNER","OLIVEIRA"],
    ["ALENCAR"],
    ["NOGUEIRA"],
    ["QUEIROZ"],
    ["SILVA","CENTRO", "BORGES"],
    ["YORK", "MACEDO", "CENTRO"],
    ["UCHOA","PACHECO","OLIVEIRA"],
    ["NOGUEIRA", "KAISER", "ESTEVES", "DUARTE"],
    ["TEIXEIRA", "MACEDO", "HOLANDA"],
    ["XAVIER", "LACERDA", "FREIRE"],
    ["LACERDA", "BORGES"],
    ["INACIO", "BORGES"],
    ["TEIXEIRA", "ALENCAR"],
    ["ZAMBONI", "YORK", "JACINTO"],
    ["WAGNER", "RIBEIRO", "NOGUEIRA", "CENTRO"],
    ["LACERDA"],
    ["YORK"],
    ["TEIXEIRA", "FREIRE"],
    ["OLIVEIRA", "CENTRO"],
    ["VASCONCELOS", "SILVA", "KAISER", "ESTEVES"],
    ["SILVA"],
]