# NÓS / POSTOS DE SAÚDE
nos = [
    "ALENCAR",
    "BORGES",
    "CENTRO",
    "DUARTE",
    "ESTEVES",
    "FREIRE",
    "GOMES",
    "HOLANDA",
    "INACIO",
    "JACINTO",
    "KAISER",
    "LACERDA",
    "MACEDO",
    "NOGUEIRA",
    "OLIVEIRA",
    "PACHECO",
    "QUEIROZ",
    "RIBEIRO",
    "SILVA",
    "TEIXEIRA",
    "UCHOA",
    "VASCONCELOS",
    "WAGNER",
    "XAVIER",
    "YORK",
    "ZAMBONI",
]

# ORDEM CRESCENTE
grafoCrescente = [
    ["GOMES", "RIBEIRO"],  # 0
    ["JACINTO", "PACHECO", "QUEIROZ"],
    ["JACINTO", "KAISER", "TEIXEIRA", "XAVIER"],
    ["MACEDO"],
    ["MACEDO", "YORK"],
    ["OLIVEIRA", "WAGNER"],
    ["ALENCAR"],
    ["NOGUEIRA"],
    ["QUEIROZ"],
    ["BORGES", "CENTRO", "SILVA"],
    ["CENTRO", "MACEDO", "YORK"],
    ["OLIVEIRA", "PACHECO", "UCHOA"],
    ["DUARTE", "ESTEVES", "KAISER", "NOGUEIRA"],
    ["HOLANDA", "MACEDO", "TEIXEIRA"],
    ["FREIRE", "LACERDA", "XAVIER"],
    ["BORGES", "LACERDA"],
    ["BORGES", "INACIO"],
    ["ALENCAR", "TEIXEIRA"],
    ["JACINTO", "YORK", "ZAMBONI"],
    ["CENTRO", "NOGUEIRA", "RIBEIRO", "WAGNER"],
    ["LACERDA"],
    ["YORK"],
    ["FREIRE", "TEIXEIRA"],
    ["CENTRO", "OLIVEIRA"],
    ["ESTEVES", "KAISER", "SILVA", "VASCONCELOS"],
    ["SILVA"],
]

# ORDEM DECRESCENTE
grafoDecrescente = [
    ["RIBEIRO","GOMES"],  # 0
    ["QUEIROZ", "PACHECO", "JACINTO"],
    ["XAVIER","TEIXEIRA", "JACINTO"],
    ["MACEDO"],
    ["YORK", "MACEDO"],
    ["WAGNER","OLIVEIRA"],
    ["ALENCAR"],
    ["NOGUEIRA"],
    ["QUEIROZ"],
    ["SILVA","CENTRO", "BORGES"],
    ["YORK", "MACEDO", "CENTRO"],
    ["UCHOA","PACHECO","OLIVEIRA"],
    ["NOGUEIRA", "KAISER", "ESTEVES", "DUARTE"],
    ["TEIXEIRA", "MACEDO", "HOLANDA"],
    ["XAVIER", "LACERDA", "FREIRE"],
    ["LACERDA", "BORGES"],
    ["INACIO", "BORGES"],
    ["TEIXEIRA", "ALENCAR"],
    ["ZAMBONI", "YORK", "JACINTO"],
    ["WAGNER", "RIBEIRO", "NOGUEIRA", "CENTRO"],
    ["LACERDA"],
    ["YORK"],
    ["TEIXEIRA", "FREIRE"],
    ["OLIVEIRA", "CENTRO"],
    ["VASCONCELOS", "SILVA", "KAISER", "ESTEVES"],
    ["SILVA"],
]



# GRAFO WITH WEIGHT
grafoPeso = [
    [["GOMES",11], ["RIBEIRO",9]],  # 0
    [["JACINTO",9], ["PACHECO",8], ["QUEIROZ",8]],
    [["JACINTO",9], ["KAISER",7], ["TEIXEIRA",5], ["XAVIER",5]],
    [["MACEDO",15]],
    [["MACEDO",11], ["YORK",9]],
    [["OLIVEIRA",10], ["WAGNER",7]],
    [["ALENCAR",11]],
    [["NOGUEIRA",9]],
    [["QUEIROZ",12]],
    [["BORGES",9], ["CENTRO",9], ["SILVA",6]],
    [["CENTRO",7], ["MACEDO",9], ["YORK",12]],
    [["OLIVEIRA",7], ["PACHECO",9], ["UCHOA",10]],
    [["DUARTE",15], ["ESTEVES",11], ["KAISER",9], ["NOGUEIRA",8]],
    [["HOLANDA",9], ["MACEDO",8], ["TEIXEIRA",10]],
    [["FREIRE",10], ["LACERDA",7], ["XAVIER",5]],
    [["BORGES",8], ["LACERDA",9]],
    [["BORGES",8], ["INACIO",12]],
    [["ALENCAR",9], ["TEIXEIRA",9]],
    [["JACINTO",6], ["YORK",9], ["ZAMBONI",9]],
    [["CENTRO",5], ["NOGUEIRA",10], ["RIBEIRO",9], ["WAGNER",8]],
    [["LACERDA",10]],
    [["YORK",15]],
    [["FREIRE",7], ["TEIXEIRA",8]],
    [["CENTRO",5], ["OLIVEIRA",5]],
    [["ESTEVES",9], ["KAISER",12], ["SILVA",9], ["VASCONCELOS",15]],
    [["SILVA",9]],
]

heuristicas = [
   [0,36,16,46,44,24,6,31,54,26,22,29,32,24,24,39,54,4,30,14,40,60,18,20,39,41]
]